name: Build (Windows SYCL)

on:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'source/*'
      - 'cpu_source/*'
      - 'rtc_source/*'
      - 'hip_source/*'
      - 'sycl_source/*'
      - '.github/workflows/build_windows_sycl.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to upload to'
        default: ''

jobs:
  build-windows:
    runs-on: windows-2022

    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Ninja
      run: pip install ninja

    - name: Download VapourSynth headers
      run: |
        curl -s -o vs.zip -L https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth-*/ vapoursynth/

    - name: Cache SYCL
      id: cache-sycl
      uses: actions/cache@v4
      with:
        path: C:\Program Files (x86)\Intel\oneAPI
        key: ${{ runner.os }}-dpcpp-2024.1

    - name: Setup SYCL
      if: steps.cache-sycl.outputs.cache-hit != 'true'
      run: |
        curl -J -o dpcpp_installer.exe https://registrationcenter-download.intel.com/akdlm/IRC_NAS/3165d8c7-088f-410f-9723-6d8ee88d9e5b/w_dpcpp-cpp-compiler_p_2024.1.2.505_offline.exe
        dpcpp_installer -s -a -s --eula accept

    - name: Setup ocloc (Gen12+)
      shell: pwsh
      run: |
        $env:PATH = "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\lib\ocloc;$env:PATH"
        "PATH=$env:PATH" | Out-File -Append -FilePath $env:GITHUB_ENV

    - name: Configure (SYCL, Gen12+)
      run: |
        ocloc compile --help

        call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat"
      
        cmake -S . -B build_sycl_gen12+ -G Ninja -LA ^
          -D CMAKE_BUILD_TYPE=Release ^
          -D ENABLE_CUDA=OFF ^
          -D ENABLE_CPU=OFF ^
          -D ENABLE_HIP=OFF ^
          -D ENABLE_SYCL=ON ^
          -D VAPOURSYNTH_INCLUDE_DIRECTORY="%cd%\vapoursynth\include" ^
          -D CMAKE_CXX_COMPILER=icx ^
          -D CMAKE_CXX_FLAGS="-ffast-math -mavx" ^
          -D CMAKE_SHARED_LINKER_FLAGS="-fsycl -fsycl-targets=spir64_gen -Xsycl-target-backend=spir64_gen \"-device gen12lp,xe-hpg,tg,tgllp\""

    - name: Build (SYCL, Gen12+)
      run: |
        call "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env\vars.bat"

        cmake --build build_sycl_gen12+ --verbose

    - name: Install (SYCL, Gen12+)
      run: echo f | xcopy build_sycl_gen12+\sycl_source\bm3dsycl.dll install\bin\bm3dsycl_gen12+.dll /f

    - name: Prepare for upload
      run: |
        mkdir artifact
        copy install\bin\*.dll artifact

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: VapourSynth-BM3DCUDA-Windows
        path: artifact

    - name: Compress artifact for release
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      run: |
        cd artifact

        :: mkdir VapourSynth-BM3DSYCL-${{ github.event.inputs.tag }}
        :: xcopy bm3dsycl_*.dll VapourSynth-BM3DSYCL-${{ github.event.inputs.tag }} /f
        :: 7z a -t7z -mx=9 ../VapourSynth-BM3DSYCL-${{ github.event.inputs.tag }}.7z VapourSynth-BM3DSYCL-${{ github.event.inputs.tag }}
        
        :: mkdir SYCL-Runtime-${{ github.event.inputs.tag }}
        :: echo f | xcopy "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\windows\bin\sycl6.dll" SYCL-Runtime-${{ github.event.inputs.tag }} /f
        :: echo f | xcopy "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\windows\bin\pi_*.dll" SYCL-Runtime-${{ github.event.inputs.tag }} /f /i
        :: echo f | xcopy "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\windows\redist\intel64_win\compiler\libmmd.dll" SYCL-Runtime-${{ github.event.inputs.tag }} /f
        :: 7z a -t7z -mx=9 ../SYCL-Runtime-${{ github.event.inputs.tag }}.7z SYCL-Runtime-${{ github.event.inputs.tag }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: |
          VapourSynth-BM3DSYCL-${{ github.event.inputs.tag }}.7z
        fail_on_unmatched_files: true
        generate_release_notes: false
        prerelease: true
